apiVersion: v1
kind: Pod
metadata:
  name: sample-auth2
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command:
      - sh
      - -c
      args:
      - tail -f /dev/null
      env:
      - name: TEST_PLAIN_VALUE
        value: fugafuga
      envFrom:
      - secretRef:
          name: sample-auth

